Repository edgar-care/frontend, pull requests merged in 2022-12, with the labels that each got.

#1 feat/ add architecture of the frontend
  .dockerignore
  .env.example
  .eslintrc.yaml
  .gitignore
  .prettierrc
  Dockerfile
  docker-compose.dev.yml
  docker-compose.yml
  next.config.js
  package.json
  pages/_app.tsx
  pages/index.tsx
  public/assets/edgar.care-logo-tabs.svg
  public/assets/edgar.care-logo.svg
  src/config/constants.ts
  src/theme/components/button.ts
  src/theme/components/link.ts
  src/theme/components/text.ts
  src/theme/foundations/borderRadius.ts
  src/theme/foundations/colors.ts
  src/theme/foundations/fonts.ts
  src/theme/foundations/shadows.ts
  src/theme/index.css
  src/theme/index.ts
  tsconfig.json
  yarn.lock
Labels: enhancement, triage

#2 feat/starting-simulation-page
  pages/simulation.tsx
Labels: enhancement

#3 fix(linter): fix eslint config & dependencies
  .eslintrc.yaml
  package.json
  yarn.lock
Labels: bug

#4 feat/add-components-theme
  pages/_app.tsx
  pages/index.tsx
  src/config/constants.ts
  src/theme/components/button.ts
  src/theme/components/text.ts
  src/theme/foundations/colors.ts
  src/theme/index.css
  src/theme/index.ts
Labels: enhancement

#5 feat/add-authmanagement
  .eslintrc.yaml
  package.json
  pages/_app.tsx
  src/components/pages/ProtectedPage.tsx
  src/components/pages/UnprotectedPage.tsx
  src/contexts/auth.ts
  src/hooks/useToggle.ts
  src/libs/auth.ts
  src/types/FetchMethod.ts
  src/types/MessageResponse.ts
  src/types/ToastStatusType.ts
  src/utils/basicFetch.ts
  yarn.lock
Labels: enhancement

#7 feat/landing page
  pages/index.tsx
  pages/solutions.tsx
  src/components/landingPage/HeadingSection.tsx
  src/components/landingPage/InfosSection.tsx
  src/components/landingPage/NavBar.tsx
  src/components/landingPage/TabCard.tsx
  src/components/pages/BasicPage.tsx
  src/components/pages/ProtectedPage.tsx
  src/components/pages/UnprotectedPage.tsx
  src/theme/components/button.ts
  src/theme/components/text.ts
  src/theme/foundations/colors.ts
  src/theme/index.css
Labels: enhancement

#10 fix/padding-landing-page
  pages/solutions.tsx
Labels: bug

#12 feat/add connection pages
  pages/connection/infos.tsx
  pages/connection/login.tsx
  pages/connection/signup.tsx
  src/components/pages/ProtectedPage.tsx
  src/components/pages/UnprotectedPage.tsx
  src/hooks/useStringState.ts
Labels: enhancement

#13 fix/peer-dependencies
  package.json
  yarn.lock
Labels: bug

#14 fix/upgrade gradient text
  pages/simulation/chat.tsx
  pages/simulation/connection.tsx
  pages/simulation/doctor.tsx
  pages/simulation/index.tsx
  pages/simulation/infos.tsx
  pages/simulation/result.tsx
  pages/solutions.tsx
  src/components/GradientText.tsx
  src/components/landingPage/HeadingSection.tsx
  src/components/landingPage/InfosSection.tsx
Labels: bug

#17 fix: husky-pre-commit
  .eslintrc.yaml
  .husky/pre-commit
Labels: bug

#16 feat/connect-simulation-to-connection-pages
  pages/simulation/connection.tsx
Labels: enhancement

#18 feat/add-temperature-infos
  pages/simulation/infos.tsx
  src/components/NumInput.tsx
Labels: enhancement

#15 feat/add simulation & connection pages
  .eslintrc.yaml
  .husky/pre-commit
  package.json
  pages/connection/infos.tsx
  pages/connection/login.tsx
  pages/connection/signup.tsx
  pages/simulation/chat.tsx
  pages/simulation/connection.tsx
  pages/simulation/doctor.tsx
  pages/simulation/index.tsx
  pages/simulation/infos.tsx
  pages/simulation/result.tsx
  pages/solutions.tsx
  public/assets/manequin-3d1.svg
  src/components/Footer.tsx
  src/components/GradientText.tsx
  src/components/NumInput.tsx
  src/components/SlideBar.tsx
  src/components/landingPage/HeadingSection.tsx
  src/components/landingPage/InfosSection.tsx
  src/components/pages/ProtectedPage.tsx
  src/components/pages/UnprotectedPage.tsx
  src/components/pages/simulation/SimulationPage.tsx
  src/components/simulationPage/AppointmentCard.tsx
  src/components/simulationPage/ChatBox.tsx
  src/components/simulationPage/ChatMessageCard.tsx
  src/components/simulationPage/CheckBox.tsx
  src/components/simulationPage/DoctorCard.tsx
  src/hooks/useStringState.ts
  src/libs/auth.ts
  src/types/simulationPage/AppointmentType.ts
  src/types/simulationPage/ChatMessageType.ts
  yarn.lock
Labels: enhancement

#20 fix(landing page): change button and redirection to simul and connection
  pages/index.tsx
  pages/solutions.tsx
  src/components/landingPage/NavBar.tsx
Labels: enhancement

#21 feat/prepare-the-backend
  pages/simulation/doctor.tsx
  src/components/simulationPage/DoctorCard.tsx
  src/types/simulationPage/DoctorType.ts
  src/utils/simulation/getAppointmentList.ts
  src/utils/simulation/getDoctorList.ts
  src/utils/simulation/setDoctor.ts
  src/utils/simulation/setInfos.ts
Labels: enhancement

#23 feat/add-connection-auth
  package.json
  pages/_app.tsx
  pages/connection/infos.tsx
  pages/connection/login.tsx
  pages/connection/signup.tsx
  pages/simulation/connection.tsx
  pages/simulation/infos.tsx
  src/components/NumInput.tsx
  src/components/pages/ProtectedPage.tsx
  src/components/pages/UnprotectedPage.tsx
  src/contexts/user.ts
  src/hooks/useCustomState.ts
  src/libs/auth.ts
  src/theme/index.css
  src/types/PatientInfos.ts
  yarn.lock
Labels: enhancement

#24 fix/add-autoconnect
  src/components/pages/ProtectedPage.tsx
  src/components/pages/UnprotectedPage.tsx
  src/libs/auth.ts
Labels: bug

#25 feat: add-chat-connection
  pages/_app.tsx
  pages/connection/infos.tsx
  pages/connection/login.tsx
  pages/connection/signup.tsx
  pages/simulation/doctor.tsx
  src/components/pages/ProtectedPage.tsx
  src/components/pages/UnprotectedPage.tsx
  src/components/simulationPage/ChatBox.tsx
  src/components/simulationPage/ChatMessageCard.tsx
  src/contexts/chat.ts
  src/libs/auth.ts
  src/libs/chat.ts
  src/types/SymptomsContextType.ts
  src/types/SymptomsType.ts
Labels: enhancement

#28 feat: add-responsive-page
  pages/app/patient/appointments.tsx
  pages/app/patient/documents.tsx
  pages/app/patient/index.tsx
  pages/app/patient/medical.tsx
  pages/connection/infos.tsx
  pages/connection/login.tsx
  pages/connection/signup.tsx
  pages/index.tsx
  pages/simulation/advise.tsx
  pages/simulation/chat.tsx
  pages/simulation/connection.tsx
  pages/simulation/doctor.tsx
  pages/simulation/index.tsx
  pages/simulation/infos.tsx
  pages/simulation/result.tsx
  pages/solutions.tsx
  src/components/Footer.tsx
  src/components/landingPage/HeadingSection.tsx
  src/components/landingPage/InfosSection.tsx
  src/components/landingPage/NavBar.tsx
  src/components/pages/BasicPage.tsx
  src/components/pages/UnprotectedPage.tsx
  src/components/pages/patient/BannerCard.tsx
  src/components/pages/patient/DashboardCard.tsx
  src/components/pages/patient/DocumentCard.tsx
  src/components/pages/patient/MedCard.tsx
  src/components/pages/patient/ModalChangeInfos.tsx
  src/components/pages/patient/NavBar.tsx
  src/components/pages/patient/QuestionCard.tsx
  src/components/pages/patient/medical/AllergiesCard.tsx
  src/components/pages/patient/medical/BodyCard.tsx
  src/components/pages/patient/medical/DatesCard.tsx
  src/components/pages/patient/medical/DiseasesCard.tsx
  src/components/pages/patient/medical/DoctorCard.tsx
  src/components/pages/patient/medical/NamesCard.tsx
  src/components/pages/patient/medical/ResponsiveNavBar.tsx
  src/components/pages/patient/medical/TreatmentCard.tsx
  src/components/pages/patient/medical/modal/UpdateMedicalModal.tsx
  src/components/pages/simulation/SimulationPage.tsx
  src/components/simulationPage/ChatBox.tsx
  src/components/simulationPage/ChatMessageCard.tsx
  src/components/simulationPage/DoctorCard.tsx
  src/theme/components/button.ts
  src/theme/index.ts
Labels: enhancement

#29 fix: fix typo
  pages/app/patient/documents.tsx
  pages/simulation/advise.tsx
  pages/simulation/index.tsx
  pages/simulation/infos.tsx
  pages/solutions.tsx
  src/components/landingPage/InfosSection.tsx
  src/components/pages/patient/NavBar.tsx
  src/components/pages/patient/medical/AllergiesCard.tsx
  src/components/pages/patient/medical/DiseasesCard.tsx
Labels: bug

#27 feat: add-page-to-download-apk
  pages/apk.tsx
  pages/solutions.tsx
  src/components/landingPage/NavBar.tsx
Labels: enhancement

#31 fix: fix-typo
  pages/app/patient/medical.tsx
  src/components/pages/patient/medical/TreatmentCard.tsx
Labels: bug

#30 feat: add v.0.5.0
  pages/apk.tsx
  pages/app/patient/appointments.tsx
  pages/app/patient/documents.tsx
  pages/app/patient/index.tsx
  pages/app/patient/medical.tsx
  pages/connection/infos.tsx
  pages/connection/login.tsx
  pages/connection/signup.tsx
  pages/index.tsx
  pages/simulation/advise.tsx
  pages/simulation/chat.tsx
  pages/simulation/connection.tsx
  pages/simulation/doctor.tsx
  pages/simulation/index.tsx
  pages/simulation/infos.tsx
  pages/simulation/result.tsx
  pages/solutions.tsx
  src/components/Footer.tsx
  src/components/landingPage/HeadingSection.tsx
  src/components/landingPage/InfosSection.tsx
  src/components/landingPage/NavBar.tsx
  src/components/pages/BasicPage.tsx
  src/components/pages/UnprotectedPage.tsx
  src/components/pages/patient/BannerCard.tsx
  src/components/pages/patient/DashboardCard.tsx
  src/components/pages/patient/DocumentCard.tsx
  src/components/pages/patient/MedCard.tsx
  src/components/pages/patient/ModalChangeInfos.tsx
  src/components/pages/patient/NavBar.tsx
  src/components/pages/patient/QuestionCard.tsx
  src/components/pages/patient/medical/AllergiesCard.tsx
  src/components/pages/patient/medical/BodyCard.tsx
  src/components/pages/patient/medical/DatesCard.tsx
  src/components/pages/patient/medical/DiseasesCard.tsx
  src/components/pages/patient/medical/DoctorCard.tsx
  src/components/pages/patient/medical/NamesCard.tsx
  src/components/pages/patient/medical/ResponsiveNavBar.tsx
  src/components/pages/patient/medical/TreatmentCard.tsx
  src/components/pages/patient/medical/modal/UpdateMedicalModal.tsx
  src/components/pages/simulation/SimulationPage.tsx
  src/components/simulationPage/ChatBox.tsx
  src/components/simulationPage/ChatMessageCard.tsx
  src/components/simulationPage/DoctorCard.tsx
  src/theme/components/button.ts
  src/theme/index.ts
Labels: enhancement

#32 feat: add v.0.5.1
  pages/_app.tsx
  pages/app/patient/medical.tsx
  pages/connection/infos.tsx
  pages/simulation/infos.tsx
  src/components/NumInput.tsx
  src/components/pages/patient/NavBar.tsx
Labels: bug

#33 feat: add v.0.5.2
  src/components/pages/patient/NavBar.tsx
Labels: bug

#34 fix: update infos
  pages/app/patient/documents.tsx
  src/components/pages/patient/medical/modal/UpdateMedicalModal.tsx
  src/components/pages/patient/medical/modal/UpdateModalNumberForm.tsx
Labels: bug

#35 fix: impossible connection when bad infos
  src/libs/auth.ts
Labels: bug

#36 fix: add v0.5.3
  .github/pull_request_template.md
  .github/workflows/eslint-tests.yaml
  src/libs/auth.ts
Labels: bug
