Repository edgar-care/frontend, pull requests merged in 2024-11, with the labels that each got.

#160 feat: add 2fa login
  .github/getting-started.md
  edgar-app/src/app/AuthProvider.tsx
  edgar-app/src/app/dashboard/documents/content.tsx
  edgar-app/src/app/dashboard/layout.tsx
  edgar-app/src/app/login-2fa/Login2faMobileProvider.tsx
  edgar-app/src/app/login-2fa/content.tsx
  edgar-app/src/app/login-2fa/page.tsx
  edgar-app/src/app/login/content.tsx
  edgar-app/src/app/onboarding/layout.tsx
  edgar-app/src/app/signup/content.tsx
  edgar-app/src/app/simulation/appointments/content.tsx
  edgar-app/src/app/simulation/chat/content.tsx
  edgar-app/src/app/simulation/conditions/content.tsx
  edgar-app/src/app/simulation/confirmation/content.tsx
  edgar-app/src/app/simulation/start/content.tsx
  edgar-app/src/assets/icons/DiagonalKeyIcon.tsx
  edgar-app/src/assets/icons/EdgarIcon.tsx
  edgar-app/src/assets/icons/MailIcon.tsx
  edgar-app/src/assets/icons/ShieldKeyIcon.tsx
  edgar-app/src/assets/illustrations/CheckIllustration.tsx
  edgar-app/src/components/connectionPage/login-2fa/Login2faCard.tsx
  edgar-app/src/components/connectionPage/login-2fa/Login2faModalPages.tsx
  edgar-app/src/components/connectionPage/login-2fa/Login2faModals.tsx
  edgar-app/src/components/connectionPage/login-2fa/pages/Login2faModalAuthenticatorPage.tsx
  edgar-app/src/components/connectionPage/login-2fa/pages/Login2faModalBackupCodePage.tsx
  edgar-app/src/components/connectionPage/login-2fa/pages/Login2faModalEmailPage.tsx
  edgar-app/src/components/connectionPage/login-2fa/pages/Login2faModalMobileAcceptedPage.tsx
  edgar-app/src/components/connectionPage/login-2fa/pages/Login2faModalMobileRefusedPage.tsx
  edgar-app/src/components/connectionPage/login-2fa/pages/Login2faModalMobileStartPage.tsx
  edgar-app/src/components/connectionPage/login-2fa/pages/Login2faModalMobileWaitingPage.tsx
  edgar-app/src/components/connectionPage/login/ConnectionLoginInputs.tsx
  edgar-app/src/components/connectionPage/signup/ConnectionSignupInputs.tsx
  edgar-app/src/components/dashboardPages/chat/ChatCard.tsx
  edgar-app/src/components/dashboardPages/chat/ChatMessageCard.tsx
  edgar-app/src/components/dashboardPages/chat/ChatMessages.tsx
  edgar-app/src/components/dashboardPages/chat/modals/StartChatContent.tsx
  edgar-app/src/components/dashboardPages/home/HomeChatCard.tsx
  edgar-app/src/components/settingsModals/ModalPages.tsx
  edgar-app/src/contexts/auth.ts
  edgar-app/src/contexts/login2faMobile.ts
  edgar-app/src/libs/auth.ts
  edgar-app/src/libs/login2faMobile.ts
  edgar-app/src/services/request/login.ts
  edgar-app/src/store/types/login.type.ts
  edgar-app/src/types/login-2fa/Login2FAResponse.ts
  edgar-app/src/types/login-2fa/Login2faMobileClassType.ts
  edgar-app/src/types/login-2fa/Login2faModalPageType.ts
  edgar-app/src/types/login-2fa/Login2faPageType.ts
  edgar-app/src/utils/api/connection/onSubmitLogin.ts
Labels: enhancement

#162 fix: pro - Dashboard Patients Fix Fontweight Ordonnance
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/prescriptions/PatientPrescriptionCard.tsx
Labels: hotfix

#161 fix: app - Dashboard Document Fix Update Illustration
  edgar-app/src/components/dashboardPages/documents/modal/UpdateDocumentHandler.tsx
Labels: hotfix

#164 fix: app - Autoreload On 2fa Mobile
  edgar-app/src/services/request/2fa.ts
  edgar-app/src/services/request/devices.ts
Labels: bug

#165 feat: app - Dashboard Disable Account
  edgar-app/src/app/dashboard/layout.tsx
  edgar-app/src/app/disable/content.tsx
  edgar-app/src/app/disable/page.tsx
  edgar-app/src/assets/illustrations/DisableAccountIllustration.tsx
  edgar-app/src/components/connectionPage/disable/DisablePageBanner.tsx
  edgar-app/src/components/connectionPage/disable/DisablePageFields.tsx
  edgar-app/src/components/settingsModals/ModalPages.tsx
  edgar-app/src/components/settingsModals/pages/account/SettingsAccountDisablePage.tsx
  edgar-app/src/services/request/auth.ts
Labels: enhancement

#169 feat: app - Dashboard Delete Account
  edgar-app/src/components/settingsModals/pages/account/SettingsAccountDeletePage.tsx
  edgar-app/src/services/request/auth.ts
Labels: enhancement

#172 fix: Update auth route with user type
  edgar-app/src/services/request/account.ts
  edgar-app/src/services/request/login.ts
  edgar-doctor/src/services/request/account.ts
  edgar-doctor/src/services/request/login.ts
Labels: bug

#173 fix: autoreload on 2fa
  edgar-app/src/components/settingsModals/ModalPages.tsx
  edgar-app/src/components/settingsModals/pages/account/SettingsAccount2FA3rdPartyEnableBackupCodesPage.tsx
  edgar-app/src/components/settingsModals/pages/account/SettingsAccount2FAEdgarEnableBackupCodePage.tsx
  edgar-app/src/components/settingsModals/pages/account/SettingsAccount2FAEmailEnableBackupCodesPage.tsx
  edgar-app/src/components/settingsModals/pages/account/SettingsAccountBackupCodesGeneratePage.tsx
  edgar-app/src/services/request/2fa.ts
  edgar-doctor/src/components/settingsModals/ModalPages.tsx
  edgar-doctor/src/components/settingsModals/pages/account/SettingsAccount2FA3rdPartyEnableBackupCodesPage.tsx
  edgar-doctor/src/components/settingsModals/pages/account/SettingsAccount2FAEdgarEnableBackupCodePage.tsx
  edgar-doctor/src/components/settingsModals/pages/account/SettingsAccount2FAEmailEnableBackupCodesPage.tsx
  edgar-doctor/src/components/settingsModals/pages/account/SettingsAccountBackupCodesGeneratePage.tsx
  edgar-doctor/src/services/request/2fa.ts
  edgar-doctor/src/services/request/devices.ts
Labels: bug

#174 feat: app - Add loading until the NLP is up
  edgar-app/src/components/simulationPages/chat/SimulationChat.tsx
  edgar-app/src/services/request/simulation.ts
Labels: enhancement

#177 feat: app/pro - add update password
  edgar-app/src/components/settingsModals/ModalPages.tsx
  edgar-app/src/components/settingsModals/pages/account/SettingsAccountResetPasswordPage.tsx
  edgar-app/src/components/settingsModals/pages/account/settingsAccountPage.ts
  edgar-app/src/services/request/account.ts
  edgar-app/src/store/types/account.type.ts
  edgar-app/src/types/password/UpdatePasswordType.ts
  edgar-doctor/src/components/settingsModals/ModalPages.tsx
  edgar-doctor/src/components/settingsModals/pages/account/SettingsAccountResetPasswordPage.tsx
  edgar-doctor/src/components/settingsModals/pages/account/settingsAccountPage.ts
  edgar-doctor/src/services/request/account.ts
  edgar-doctor/src/store/types/account.type.ts
  edgar-doctor/src/types/app/login/UpdatePasswordType.ts
Labels: enhancement

#178 fix: pro - Check Credentials
  edgar-doctor/src/components/app/connectionPage/signup/ConnectionSignupInputs.tsx
  edgar-doctor/src/components/app/connectionPage/signup/ConnectionSignupRegister.tsx
Labels: bug

#176 feat: add v.1.7.1
  .github/workflows/CI-frontend-app.yaml
  .github/workflows/CI-frontend-pro.yaml
  edgar-app/.env.example
  edgar-app/src/app/dashboard/layout.tsx
  edgar-app/src/app/login-2fa/content.tsx
  edgar-app/src/components/connectionPage/login/ConnectionLoginInputs.tsx
  edgar-app/src/components/dashboardPages/documents/modal/AddDocumentHandler.tsx
  edgar-app/src/components/dashboardPages/treatments/AddTreatmentPeriodInputs.tsx
  edgar-app/src/components/dashboardPages/treatments/UpdateTreatmentHandler.tsx
  edgar-app/src/components/settingsModals/ModalPages.tsx
  edgar-app/src/components/settingsModals/pages/account/SettingsAccountResetPasswordPage.tsx
  edgar-app/src/components/settingsModals/pages/account/settingsAccountPage.ts
  edgar-app/src/config/constants.ts
  edgar-app/src/services/request/account.ts
  edgar-app/src/store/types/account.type.ts
  edgar-app/src/types/MessageResponse.ts
  edgar-app/src/types/password/UpdatePasswordType.ts
  edgar-app/src/utils/api/connection/onSubmitLogin.ts
  edgar-app/src/utils/crypt.ts
  edgar-doctor/.env.example
  edgar-doctor/src/app/login-2fa/content.tsx
  edgar-doctor/src/components/app/connectionPage/login/ConnectionLoginInputs.tsx
  edgar-doctor/src/components/app/connectionPage/signup/ConnectionSignupInputs.tsx
  edgar-doctor/src/components/app/connectionPage/signup/ConnectionSignupRegister.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/AddPatientHandler.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/documents/modals/PatientAddDocumentHandler.tsx
  edgar-doctor/src/components/settingsModals/ModalPages.tsx
  edgar-doctor/src/components/settingsModals/pages/account/SettingsAccountResetPasswordPage.tsx
  edgar-doctor/src/components/settingsModals/pages/account/settingsAccountPage.ts
  edgar-doctor/src/config/constants.ts
  edgar-doctor/src/services/request/account.ts
  edgar-doctor/src/store/types/account.type.ts
  edgar-doctor/src/types/MessageResponse.ts
  edgar-doctor/src/types/app/login/UpdatePasswordType.ts
  edgar-doctor/src/utils/api/connection/onSubmitLogin.ts
  edgar-doctor/src/utils/crypt.ts
Labels: bug
