Repository edgar-care/frontend, pull requests merged in 2024-05, with the labels that each got.

#95 feat: app - Add treatments calendar
  edgar-app/cypress/e2e/desktop/dashboard/navigation.cy.ts
  edgar-app/cypress/e2e/desktop/dashboard/treatmentsPage.cy.ts
  edgar-app/cypress/e2e/mobile/dashboard/navigation.cy.ts
  edgar-app/cypress/e2e/mobile/dashboard/treatmentsPage.cy.ts
  edgar-app/cypress/utils/setupMedicalInfo.ts
  edgar-app/src/app/dashboard/layout.tsx
  edgar-app/src/app/dashboard/treatments/content.tsx
  edgar-app/src/app/dashboard/treatments/page.tsx
  edgar-app/src/assets/icons/MedicineIcon.tsx
  edgar-app/src/components/dashboardPages/treatments/TreatmentsCalendar.tsx
  edgar-app/src/components/dashboardPages/treatments/TreatmentsCalendarDay.tsx
  edgar-app/src/components/dashboardPages/treatments/TreatmentsCheckboxTreatment.tsx
  edgar-app/src/components/navigation/Navbar.tsx
  edgar-app/src/services/apiService.ts
  edgar-app/src/services/request/medical.ts
  edgar-app/src/services/request/treatments.ts
  edgar-app/src/store/types/medical.type.ts
  edgar-app/src/store/types/treatments.type.ts
  edgar-app/src/types/dashboard/medical/HealthIssueType.ts
  edgar-app/src/types/dashboard/treatments/TreatmentFollowUpType.ts
  edgar-app/src/types/dashboard/treatments/TreatmentSubNavigationType.ts
  edgar-app/src/utils/app/dashboard/treatments/getDateOfTheDay.ts
  edgar-app/src/utils/app/dashboard/treatments/getPeriodOfTheDay.ts
  edgar-app/src/utils/app/dashboard/treatments/groupFollowUpTreatmentsByDayPeriod.ts
  edgar-app/src/utils/app/dashboard/treatments/groupTreatmentsByDayPeriod.ts
Labels: enhancement

#87 feat: app - Dashboard Home Treatment Follow Up
  edgar-app/src/app/dashboard/content.tsx
  edgar-app/src/assets/icons/WarningIcon.tsx
  edgar-app/src/components/dashboardPages/home/HomeChatCard.tsx
  edgar-app/src/components/dashboardPages/home/HomeTreatmentsCard.tsx
  edgar-app/src/components/dashboardPages/treatments/TreatmentsCalendarDay.tsx
Labels: enhancement

#98 fix: pro - Dashboard Display Appointments
  edgar-doctor/src/components/app/dashboardPages/appointments/AppointmentsCalendarCard.tsx
Labels: hotfix

#100 feat: app - Send message to a doctor
  .github/workflows/CI-frontend-app.yaml
  edgar-app/cypress/e2e/desktop/dashboard/navigation.cy.ts
  edgar-app/cypress/e2e/mobile/dashboard/navigation.cy.ts
  edgar-app/src/app/dashboard/chat/ChatProvider.tsx
  edgar-app/src/app/dashboard/chat/content.tsx
  edgar-app/src/assets/icons/PaperPlaneIcon.tsx
  edgar-app/src/components/dashboardPages/chat/ChatMessages.tsx
  edgar-app/src/components/dashboardPages/home/HomeChatCard.tsx
  edgar-app/src/libs/chat.ts
  edgar-app/src/types/dashboard/chat/ChatClassType.ts
Labels: enhancement

#102 feat: pro: Add diagnostic page
  edgar-doctor/src/app/dashboard/diagnostics/content.tsx
  edgar-doctor/src/app/dashboard/diagnostics/page.tsx
  edgar-doctor/src/assets/icons/FileIcon.tsx
  edgar-doctor/src/assets/icons/HeartPulseIcon.tsx
  edgar-doctor/src/assets/icons/TreatmentIcon.tsx
  edgar-doctor/src/assets/illustrations/AddHealthIssueIllustration.tsx
  edgar-doctor/src/assets/illustrations/BlueCalendarIllustration.tsx
  edgar-doctor/src/components/app/dashboardPages/appointments/AppointmentCard.tsx
  edgar-doctor/src/components/app/dashboardPages/appointments/CalendarAppointmentCard.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/DiagnosticBadge.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/DiagnosticCard.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/DiagnosticTitleCard.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/Diagnostics.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/DiagnosticsView.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/chat/DiagnosticLogs.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/medicalInfo/DiagnosticMedicalInfo.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/medicalInfo/DiagnosticMedicalInfoHealth.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/medicalInfo/DiagnosticMedicalInfoPersonal.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/medicalInfo/medicalAntecedents/MedicalAntecedentsCard.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/medicalInfo/medicalAntecedents/MedicalAntecedentsInfoDrawer.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/medicalInfo/medicalAntecedents/medicine/MedicineCard.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/medicalInfo/medicalAntecedents/medicine/MedicineSmallCard.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/DiagnosticDrawer.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/DiagnosticHandler.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/DiagnosticModal.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/DiagnosticModalContent.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/DiagnosticModalFooter.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/DiagnosticModalHeader.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/cancelModal/DiagnosticCancelDrawer.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/cancelModal/DiagnosticCancelHandler.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/cancelModal/DiagnosticCancelModal.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/cancelModal/DiagnosticCancelModalContent.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/cancelModal/DiagnosticCancelModalFooter.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/cancelModal/fields/DiagnosticCancelModalHealMethodInput.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/cancelModal/fields/DiagnosticCancelModalReasonInput.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/validateModal/DiagnosticValidateDrawer.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/validateModal/DiagnosticValidateHandler.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/validateModal/DiagnosticValidateModal.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/validateModal/DiagnosticValidateModalContent.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/modals/validateModal/DiagnosticValidateModalFooter.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/summary/DiagnosticSummary.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/summary/DiagnosticSummarySuggestedDiseasesCard.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/summary/DiagnosticSummarySymptoms.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/summary/DiagnosticSymptomCard.tsx
  edgar-doctor/src/components/navigation/Navbar.tsx
  edgar-doctor/src/components/progress/CustomProgress.tsx
  edgar-doctor/src/services/request/diagnostics.ts
  edgar-doctor/src/services/request/medicines.ts
  edgar-doctor/src/store/types/diagnostics.type.ts
  edgar-doctor/src/store/types/medicines.type.ts
  edgar-doctor/src/theme/components/modal.ts
  edgar-doctor/src/theme/components/textarea.ts
  edgar-doctor/src/theme/index.ts
  edgar-doctor/src/types/app/dashboard/diagnostics/DiagnosticSummaryType.ts
  edgar-doctor/src/types/app/dashboard/diagnostics/DiagnosticsSubNavigationType.ts
  edgar-doctor/src/types/app/dashboard/diagnostics/MedicineType.ts
  edgar-doctor/src/types/app/dashboard/patients/PatientType.ts
  edgar-doctor/src/utils/app/dashboard/diagnostic/displayMedicineUnit.ts
Labels: enhancement

#97 feat: pro - Dashboard Patient Appointments
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/PatientsSubViewAppointments.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/PatientsSubViewManager.tsx
Labels: enhancement

#105 feat: pro: Add patient document subview
  edgar-doctor/src/assets/illustrations/AddDocumentIllustration.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/PatientsCard.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/PatientsSubViewManager.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/documents/PatientDocumentCard.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/documents/PatientsSubViewDocuments.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/documents/modals/PatientAddDocumentDrawer.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/documents/modals/PatientAddDocumentHandler.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/documents/modals/PatientAddDocumentModal.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/documents/modals/PatientAddDocumentModalContent.tsx
  edgar-doctor/src/services/request/patients.ts
  edgar-doctor/src/store/types/patients.type.ts
  edgar-doctor/src/theme/components/select.ts
  edgar-doctor/src/theme/index.ts
  edgar-doctor/src/types/app/dashboard/patients/documents/DocumentCategoryType.ts
  edgar-doctor/src/types/app/dashboard/patients/documents/DocumentTypeType.ts
  edgar-doctor/src/types/app/dashboard/patients/documents/PatientDocumentType.ts
Labels: enhancement

#107 feat: fix UI
  edgar-app/src/components/dashboardPages/appointments/AppointmentCard.tsx
  edgar-app/src/components/dashboardPages/appointments/AppointmentDoctorCard.tsx
  edgar-app/src/components/dashboardPages/appointments/AppointmentsCalendarCard.tsx
  edgar-app/src/components/dashboardPages/appointments/CalendarAppointmentCard.tsx
  edgar-doctor/src/components/app/dashboardPages/appointments/AppointmentSlots.tsx
  edgar-doctor/src/components/app/dashboardPages/appointments/modals/UpdateAppointmentContent.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/chat/DiagnosticLogs.tsx
  edgar-doctor/src/components/app/dashboardPages/diagnostics/medicalInfo/DiagnosticMedicalInfo.tsx
  edgar-doctor/src/services/request/slots.ts
  edgar-doctor/src/store/types/slots.type.ts
Labels: bug

#108 feat: pro: Add a patient
  edgar-doctor/src/app/dashboard/patients/content.tsx
  edgar-doctor/src/assets/icons/AddIcon.tsx
  edgar-doctor/src/assets/illustrations/AddMedicalAntecedentsIllustration.tsx
  edgar-doctor/src/assets/illustrations/AddPatientIllustration.tsx
  edgar-doctor/src/assets/illustrations/PeopleIllustration.tsx
  edgar-doctor/src/components/AdvancedSelector.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/AddPatientDrawer.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/AddPatientHandler.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/AddPatientModal.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/AddPatientModalContent.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/AddPatientModalMedicalAntecedents.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/AddPatientModalSecondContent.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/SelectMedicalAntecedentsContent.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/SelectMedicalAntecedentsDrawer.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/SelectMedicalAntecedentsHandler.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/SelectMedicalAntecedentsModal.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/AddPatientModalBirthdateInput.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/AddPatientModalFirstnameInput.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/AddPatientModalMailInput.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/AddPatientModalNameInput.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/AddPatientModalPrimaryDoctorInput.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/AddPatientModalSexInput.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/AddPatientModalSizeInput.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/AddPatientModalWeightInput.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/SelectMedicalAntecedentsMedicineInput.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/SelectMedicalAntecedentsMedicineInputCard.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/SelectMedicalAntecedentsNameInput.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/SelectMedicalAntecedentsStillRelevantInput.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/medicalAntecedents/MedicalAntecedentsCard.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/medicalAntecedents/MedicalAntecedentsInfoDrawer.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/medicine/MedicineCard.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/medicine/MedicineCardDays.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/medicine/MedicineCardPeriods.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/medicine/MedicineSmallCard.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/medicine/ReadonlyMedicineCard.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/primaryDoctor/SelectPrimaryDoctorCard.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/primaryDoctor/SelectPrimaryDoctorContent.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/primaryDoctor/SelectPrimaryDoctorDrawer.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/primaryDoctor/SelectPrimaryDoctorHandler.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/modal/forms/primaryDoctor/SelectPrimaryDoctorModal.tsx
  edgar-doctor/src/components/stepper/Stepper.tsx
  edgar-doctor/src/services/request/doctor.ts
  edgar-doctor/src/services/request/patients.ts
  edgar-doctor/src/store/types/medicine.type.ts
  edgar-doctor/src/store/types/patients.type.ts
  edgar-doctor/src/theme/components/input.ts
  edgar-doctor/src/types/AdvancedSelectorOptionType.ts
  edgar-doctor/src/types/app/dashboard/medical/MedicineType.ts
Labels: enhancement

#109 feat: pro: Add patient medical info subview
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/PatientsSubViewManager.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/chat/PatientsSubViewChat.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/medicalInfo/PatientsSubViewMedicalInfo.tsx
Labels: enhancement

#110 feat: pro: Delete a patient
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/deletePatient/DeletePatientDrawer.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/deletePatient/DeletePatientHandler.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/deletePatient/DeletePatientModal.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/navigation/PatientsSubViewNavigation.tsx
  edgar-doctor/src/components/app/dashboardPages/patients/subViews/navigation/PatientsSubViewNavigationHandler.tsx
  edgar-doctor/src/services/request/patients.ts
Labels: enhancement
